#!/bin/bash
DATE_FORMAT=$(date +"%Y-%m-%d")
 
# MySQL server credentials
MYSQL_HOST="172.31.6.70"
MYSQL_PORT="3306"
MYSQL_USER="dkzuser"
MYSQL_PASSWORD="DKZ-u!23"
 
# Path to local backup directory
LOCAL_BACKUP_DIR="/backupfors3"
 
# Set s3 bucket name and directory path
S3_BUCKET_NAME="backup-mariadb-live"
S3_BUCKET_PATH="backup-db"
 
# Number of days to store local backup files
#BACKUP_RETAIN_DAYS=7 
 
# Use a single database or space separated database's names
DATABASES="dikazodb"
 
##### Do not change below this line
 
mkdir -p ${LOCAL_BACKUP_DIR}/${DATE_FORMAT}
 
LOCAL_DIR=${LOCAL_BACKUP_DIR}/${DATE_FORMAT}
REMOTE_DIR=s3://${S3_BUCKET_NAME}/${S3_BUCKET_PATH}
 
for db in $DATABASES; do
   mysqldump \
        -h ${MYSQL_HOST} \
        -P ${MYSQL_PORT} \
        -u ${MYSQL_USER} \
        -p${MYSQL_PASSWORD} \
        --single-transaction ${db}   > ${LOCAL_DIR}/${db}-${DATE_FORMAT}.sql
 
        aws s3 cp ${LOCAL_DIR}/${db}-${DATE_FORMAT}.sql ${REMOTE_DIR}/${DATE_FORMAT}/
done
 
DBDELDATE=`date +"${DATE_FORMAT}" --date="${BACKUP_RETAIN_DAYS} days ago"`
 
if [ ! -z ${LOCAL_BACKUP_DIR} ]; then
 cd ${LOCAL_BACKUP_DIR}
 if [ ! -z ${DBDELDATE} ] && [ -d ${DBDELDATE} ]; then
 rm -rf ${DBDELDATE}
 
 fi
fi
